import { Inter } from "next/font/google";
// import "./globals.css";
import {Registry as StyledComponentRegistry} from '../style/registry'

const inter = Inter({ subsets: ["latin"] });
//추가
const queryClient = new QueryCli

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ 
  children 
}: {
  children : React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <StyledComponentRegistry>{children}</StyledComponentRegistry>
      </body>
    </html>
  );
}
